// <auto-generated />
using System;
using KSZPL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KSZPL.Data.Migrations
{
    [DbContext(typeof(KSZPLDbContext))]
    [Migration("20190321202435_othertables")]
    partial class othertables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KSZPL.Data.Models.Patient", b =>
                {
                    b.Property<decimal>("Id");

                    b.Property<string>("Address");

                    b.Property<DateTime>("DateBirth");

                    b.Property<DateTime>("DateRegister");

                    b.Property<string>("Email");

                    b.Property<string>("Imie");

                    b.Property<decimal>("NIP");

                    b.Property<string>("Nazwisko");

                    b.Property<decimal>("PESEL");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("KSZPL.Data.Models.PatientCard", b =>
                {
                    b.Property<decimal>("Id");

                    b.Property<string>("HistoryTreatment");

                    b.Property<decimal>("IdPatient");

                    b.Property<decimal>("IdUser");

                    b.HasKey("Id");

                    b.ToTable("PatientCards");
                });

            modelBuilder.Entity("KSZPL.Data.Models.Recipe", b =>
                {
                    b.Property<decimal>("Id");

                    b.Property<DateTime>("DateRelease");

                    b.Property<decimal>("IdPatientCard");

                    b.Property<decimal>("IdUser");

                    b.Property<string>("PrescribedMedicines");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("KSZPL.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KSZPL.Data.Models.Visit", b =>
                {
                    b.Property<decimal>("Id");

                    b.Property<DateTime>("DateVisit");

                    b.Property<string>("Description");

                    b.Property<decimal>("IdPatient");

                    b.Property<decimal>("IdUser");

                    b.Property<string>("Place");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
